# Generated by Django 3.2.4 on 2021-07-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Тип')),
                ('reason', models.CharField(max_length=10, verbose_name='Вид')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('pay_method', models.CharField(max_length=5, verbose_name='оплата')),
            ],
            options={
                'verbose_name': 'Карточки',
                'verbose_name_plural': 'Карточки',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Loadout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_xls', models.ImageField(blank=True, null=True, upload_to='')),
                ('sch_xls', models.ImageField(blank=True, null=True, upload_to='')),
                ('st_images', models.ImageField(blank=True, null=True, upload_to='')),
                ('sch_images', models.ImageField(blank=True, null=True, upload_to='')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-pub_date'],
            },
        ),
    ]
